apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}--eladtest
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--eladtest
    spec:
      containers:
      - image: {{ .Values.containers.image }}
        name: {{ .Release.Name }}--apache
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: {{ .Values.resources.cpu }}
            memory: {{ .Values.resources.memory }}
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
        volumeMounts:
        - name: std-apache-volume
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: std-apache-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}--std-apache-pvc
